/** @format */

import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" mx-auto max-w-[1366px] min-h-[100vh] px-[60px]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
